version: '3.8'

services:
  c1:
    build: ./C1
    container_name: C1
    stdin_open: true
    tty: true
    networks:
      - ssh_network
    volumes:
      - ./capturas/c1:/capturas

  c2:
    build: ./C2
    container_name: C2
    stdin_open: true
    tty: true
    networks:
      - ssh_network
    volumes:
      - ./capturas/c2:/capturas

  c3:
    build: ./C3
    container_name: C3
    stdin_open: true
    tty: true
    networks:
      - ssh_network
    volumes:
      - ./capturas/c3:/capturas

  c4-s1:
    build: ./C4-S1
    container_name: C4-S1
    stdin_open: true
    tty: true
    privileged: true
    networks:
      - ssh_network
    ports:
      - "2222:22"
    volumes:
      - ./capturas/c4-s1:/capturas

networks:
  ssh_network:
    driver: bridge